'==============================================================================
'  WARNING!!  This file is overwritten by the Block UI Styler while generating
'  the automation code. Any modifications to this file will be lost after
'  generating the code again.
'
'       Filename:  F:\VB.NET\Prop.vb
'
'        This file was generated by the NX Block UI Styler
'        Created by: dudkin_m
'              Version: NX 10
'              Date: 08-28-2019  (Format: mm-dd-yyyy)
'              Time: 11:24 (Format: hh-mm)
'
'==============================================================================

'==============================================================================
'  Purpose:  This TEMPLATE file contains VB.NET source to guide you in the
'  construction of your Block application dialog. The generation of your
'  dialog file (.dlx extension) is the first step towards dialog construction
'  within NX.  You must now create a NX Open application that
'  utilizes this file (.dlx).
'
'  The information in this file provides you with the following:
'
'  1.  Help on how to load and display your Block UI Styler dialog in NX
'      using APIs provided in NXOpen.BlockStyler namespace
'  2.  The empty callback methods (stubs) associated with your dialog items
'      have also been placed in this file. These empty methods have been
'      created simply to start you along with your coding requirements.
'      The method name, argument list and possible return values have already
'      been provided for you.
'==============================================================================

'------------------------------------------------------------------------------
'These imports are needed for the following template code
'------------------------------------------------------------------------------
Option Strict Off
Imports System
Imports NXOpen
Imports NXOpen.BlockStyler

'------------------------------------------------------------------------------
'Represents Block Styler application class
'------------------------------------------------------------------------------
Public Class Prop
    'class members
    Private Shared theSession As Session
    Private Shared theUI As UI
    Private theDlxFileName As String
    Private theDialog As NXOpen.BlockStyler.BlockDialog
    Private group As NXOpen.BlockStyler.Group' Block type: Group
    Private string02 As NXOpen.BlockStyler.StringBlock' Block type: String
    Private enum01 As NXOpen.BlockStyler.Enumeration' Block type: Enumeration
    Private separator03 As NXOpen.BlockStyler.Separator' Block type: Separator
    Private button0 As NXOpen.BlockStyler.Button' Block type: Button
    Private group1 As NXOpen.BlockStyler.Group' Block type: Group
    Private string0 As NXOpen.BlockStyler.StringBlock' Block type: String
    Private button01 As NXOpen.BlockStyler.Button' Block type: Button
    Private string01 As NXOpen.BlockStyler.StringBlock' Block type: String
    Private button02 As NXOpen.BlockStyler.Button' Block type: Button
    Private separator0 As NXOpen.BlockStyler.Separator' Block type: Separator
    Private separator01 As NXOpen.BlockStyler.Separator' Block type: Separator
    Private button03 As NXOpen.BlockStyler.Button' Block type: Button
    Private group2 As NXOpen.BlockStyler.Group' Block type: Group
    Private enum0 As NXOpen.BlockStyler.Enumeration' Block type: Enumeration
    Private enum02 As NXOpen.BlockStyler.Enumeration' Block type: Enumeration
    Private enum03 As NXOpen.BlockStyler.Enumeration' Block type: Enumeration
    Private enum04 As NXOpen.BlockStyler.Enumeration' Block type: Enumeration
    Private separator02 As NXOpen.BlockStyler.Separator' Block type: Separator
    Private button04 As NXOpen.BlockStyler.Button' Block type: Button
    Private group3 As NXOpen.BlockStyler.Group' Block type: Group
    Private string03 As NXOpen.BlockStyler.StringBlock' Block type: String
    Private button05 As NXOpen.BlockStyler.Button' Block type: Button
    Private separator04 As NXOpen.BlockStyler.Separator' Block type: Separator
    Private button06 As NXOpen.BlockStyler.Button' Block type: Button
    Private group4 As NXOpen.BlockStyler.Group' Block type: Group
    Private enum05 As NXOpen.BlockStyler.Enumeration' Block type: Enumeration
    Private multiline_string0 As NXOpen.BlockStyler.MultilineString' Block type: Multiline String
    Private separator05 As NXOpen.BlockStyler.Separator' Block type: Separator
    Private button07 As NXOpen.BlockStyler.Button' Block type: Button
    
#Region "Block Styler Dialog Designer generator code"
    '------------------------------------------------------------------------------
    'Constructor for NX Styler class
    '------------------------------------------------------------------------------
    Public Sub New()
        Try
        
            theSession = Session.GetSession()
            theUI = UI.GetUI()
            theDlxFileName = "Prop.dlx"
            theDialog = theUI.CreateDialog(theDlxFileName)
            theDialog.AddApplyHandler(AddressOf apply_cb)
            theDialog.AddOkHandler(AddressOf ok_cb)
            theDialog.AddUpdateHandler(AddressOf update_cb)
            theDialog.AddInitializeHandler(AddressOf initialize_cb)
            theDialog.AddDialogShownHandler(AddressOf dialogShown_cb)
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            Throw ex
        End Try
    End Sub
#End Region
    
    '------------------------------- DIALOG LAUNCHING ---------------------------------
    '
    '    Before invoking this application one needs to open any part/empty part in NX
    '    because of the behavior of the blocks.
    '
    '    Make sure the dlx file is in one of the following locations:
    '        1.) From where NX session is launched
    '        2.) $UGII_USER_DIR/application
    '        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
    '            recommended. This variable is set to a full directory path to a file 
    '            containing a list of root directories for all custom applications.
    '            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
    '
    '    You can create the dialog using one of the following way:
    '
    '    1. Journal Replay
    '
    '        1) Replay this file through Tool->Journal->Play Menu.
    '
    '    2. USER EXIT
    '
    '        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
    '        2) Invoke the Shared Library through File->Execute->NX Open menu.
    '
    '------------------------------------------------------------------------------
    Public Shared Sub Main()
        Dim theProp As Prop = Nothing
        Try
        
            theProp = New Prop()
            ' The following method shows the dialog immediately
            theProp.Show()
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        Finally
            If theProp IsNot Nothing Then 
                theProp.Dispose()
                theProp = Nothing
            End If
        End Try
    End Sub
    '------------------------------------------------------------------------------
    ' This method specifies how a shared image is unloaded from memory
    ' within NX. This method gives you the capability to unload an
    ' internal NX Open application or user  exit from NX. Specify any
    ' one of the three constants as a return value to determine the type
    ' of unload to perform:
    '
    '
    '    Immediately : unload the library as soon as the automation program has completed
    '    Explicitly  : unload the library from the "Unload Shared Image" dialog
    '    AtTermination : unload the library when the NX session terminates
    '
    '
    ' NOTE:  A program which associates NX Open applications with the menubar
    ' MUST NOT use this option since it will UNLOAD your NX Open application image
    ' from the menubar.
    '------------------------------------------------------------------------------
    Public Shared Function GetUnloadOption(ByVal arg As String) As Integer
        'Return CType(Session.LibraryUnloadOption.Explicitly, Integer)
         Return CType(Session.LibraryUnloadOption.Immediately, Integer)
        ' Return CType(Session.LibraryUnloadOption.AtTermination, Integer)
    End Function
    '------------------------------------------------------------------------------
    ' Following method cleanup any housekeeping chores that may be needed.
    ' This method is automatically called by NX.
    '------------------------------------------------------------------------------
    Public Shared Sub UnloadLibrary(ByVal arg As String)
        Try
        
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Sub
    
    '------------------------------------------------------------------------------
    'This method shows the dialog on the screen
    '------------------------------------------------------------------------------
    Public Sub Show()
        Try
        
            theDialog.Show
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Sub
    
    '------------------------------------------------------------------------------
    'Method Name: Dispose
    '------------------------------------------------------------------------------
    Public Sub Dispose()
        If theDialog IsNot Nothing Then 
            theDialog.Dispose()
            theDialog = Nothing
        End If
    End Sub
    
    '------------------------------------------------------------------------------
    '---------------------Block UI Styler Callback Functions--------------------------
    '------------------------------------------------------------------------------
    
    '------------------------------------------------------------------------------
    'Callback Name: initialize_cb
    '------------------------------------------------------------------------------
    Public Sub initialize_cb()
        Try
        
            group = CType(theDialog.TopBlock.FindBlock("group"), NXOpen.BlockStyler.Group)
            string02 = CType(theDialog.TopBlock.FindBlock("string02"), NXOpen.BlockStyler.StringBlock)
            enum01 = CType(theDialog.TopBlock.FindBlock("enum01"), NXOpen.BlockStyler.Enumeration)
            separator03 = CType(theDialog.TopBlock.FindBlock("separator03"), NXOpen.BlockStyler.Separator)
            button0 = CType(theDialog.TopBlock.FindBlock("button0"), NXOpen.BlockStyler.Button)
            group1 = CType(theDialog.TopBlock.FindBlock("group1"), NXOpen.BlockStyler.Group)
            string0 = CType(theDialog.TopBlock.FindBlock("string0"), NXOpen.BlockStyler.StringBlock)
            button01 = CType(theDialog.TopBlock.FindBlock("button01"), NXOpen.BlockStyler.Button)
            string01 = CType(theDialog.TopBlock.FindBlock("string01"), NXOpen.BlockStyler.StringBlock)
            button02 = CType(theDialog.TopBlock.FindBlock("button02"), NXOpen.BlockStyler.Button)
            separator0 = CType(theDialog.TopBlock.FindBlock("separator0"), NXOpen.BlockStyler.Separator)
            separator01 = CType(theDialog.TopBlock.FindBlock("separator01"), NXOpen.BlockStyler.Separator)
            button03 = CType(theDialog.TopBlock.FindBlock("button03"), NXOpen.BlockStyler.Button)
            group2 = CType(theDialog.TopBlock.FindBlock("group2"), NXOpen.BlockStyler.Group)
            enum0 = CType(theDialog.TopBlock.FindBlock("enum0"), NXOpen.BlockStyler.Enumeration)
            enum02 = CType(theDialog.TopBlock.FindBlock("enum02"), NXOpen.BlockStyler.Enumeration)
            enum03 = CType(theDialog.TopBlock.FindBlock("enum03"), NXOpen.BlockStyler.Enumeration)
            enum04 = CType(theDialog.TopBlock.FindBlock("enum04"), NXOpen.BlockStyler.Enumeration)
            separator02 = CType(theDialog.TopBlock.FindBlock("separator02"), NXOpen.BlockStyler.Separator)
            button04 = CType(theDialog.TopBlock.FindBlock("button04"), NXOpen.BlockStyler.Button)
            group3 = CType(theDialog.TopBlock.FindBlock("group3"), NXOpen.BlockStyler.Group)
            string03 = CType(theDialog.TopBlock.FindBlock("string03"), NXOpen.BlockStyler.StringBlock)
            button05 = CType(theDialog.TopBlock.FindBlock("button05"), NXOpen.BlockStyler.Button)
            separator04 = CType(theDialog.TopBlock.FindBlock("separator04"), NXOpen.BlockStyler.Separator)
            button06 = CType(theDialog.TopBlock.FindBlock("button06"), NXOpen.BlockStyler.Button)
            group4 = CType(theDialog.TopBlock.FindBlock("group4"), NXOpen.BlockStyler.Group)
            enum05 = CType(theDialog.TopBlock.FindBlock("enum05"), NXOpen.BlockStyler.Enumeration)
            multiline_string0 = CType(theDialog.TopBlock.FindBlock("multiline_string0"), NXOpen.BlockStyler.MultilineString)
            separator05 = CType(theDialog.TopBlock.FindBlock("separator05"), NXOpen.BlockStyler.Separator)
            button07 = CType(theDialog.TopBlock.FindBlock("button07"), NXOpen.BlockStyler.Button)
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Sub
    
    '------------------------------------------------------------------------------
    'Callback Name: dialogShown_cb
    'This callback is executed just before the dialog launch. Thus any value set 
    'here will take precedence and dialog will be launched showing that value. 
    '------------------------------------------------------------------------------
    Public Sub dialogShown_cb()
        Try
        
            '---- Enter your callback code here -----
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Sub
    
    '------------------------------------------------------------------------------
    'Callback Name: apply_cb
    '------------------------------------------------------------------------------
    Public Function apply_cb() As Integer
        Dim errorCode as Integer = 0
        Try
        
            '---- Enter your callback code here -----
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            errorCode = 1
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
        apply_cb = errorCode
    End Function
    
    '------------------------------------------------------------------------------
    'Callback Name: update_cb
    '------------------------------------------------------------------------------
    Public Function update_cb(ByVal block As NXOpen.BlockStyler.UIBlock) As Integer
        Try
        
            If block Is string02 Then
            '---- Enter your code here -----
            
            ElseIf block Is enum01 Then
            '---- Enter your code here -----
            
            ElseIf block Is separator03 Then
            '---- Enter your code here -----
            
            ElseIf block Is button0 Then
            '---- Enter your code here -----
            
            ElseIf block Is string0 Then
            '---- Enter your code here -----
            
            ElseIf block Is button01 Then
            '---- Enter your code here -----
            
            ElseIf block Is string01 Then
            '---- Enter your code here -----
            
            ElseIf block Is button02 Then
            '---- Enter your code here -----
            
            ElseIf block Is separator0 Then
            '---- Enter your code here -----
            
            ElseIf block Is separator01 Then
            '---- Enter your code here -----
            
            ElseIf block Is button03 Then
            '---- Enter your code here -----
            
            ElseIf block Is enum0 Then
            '---- Enter your code here -----
            
            ElseIf block Is enum02 Then
            '---- Enter your code here -----
            
            ElseIf block Is enum03 Then
            '---- Enter your code here -----
            
            ElseIf block Is enum04 Then
            '---- Enter your code here -----
            
            ElseIf block Is separator02 Then
            '---- Enter your code here -----
            
            ElseIf block Is button04 Then
            '---- Enter your code here -----
            
            ElseIf block Is string03 Then
            '---- Enter your code here -----
            
            ElseIf block Is button05 Then
            '---- Enter your code here -----
            
            ElseIf block Is separator04 Then
            '---- Enter your code here -----
            
            ElseIf block Is button06 Then
            '---- Enter your code here -----
            
            ElseIf block Is enum05 Then
            '---- Enter your code here -----
            
            ElseIf block Is multiline_string0 Then
            '---- Enter your code here -----
            
            ElseIf block Is separator05 Then
            '---- Enter your code here -----
            
            ElseIf block Is button07 Then
            '---- Enter your code here -----
            
            End If
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
        update_cb = 0
    End Function
    
    '------------------------------------------------------------------------------
    'Callback Name: ok_cb
    '------------------------------------------------------------------------------
    Public Function ok_cb() As Integer
        Dim errorCode as Integer = 0
        Try
        
            '---- Enter your callback code here -----
            errorCode = apply_cb()
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            errorCode = 1
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
        ok_cb = errorCode
    End Function
    
    '------------------------------------------------------------------------------
    'Function Name: GetBlockProperties
    'Returns the propertylist of the specified BlockID
    '------------------------------------------------------------------------------
    Public Function GetBlockProperties(ByVal blockID As String) As PropertyList
        GetBlockProperties = Nothing
        Try
        
            GetBlockProperties = theDialog.GetBlockProperties(blockID)
        
        Catch ex As Exception
        
            '---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString)
        End Try
    End Function
    
End Class
